name: Preview Deploy

on:
  workflow_run:
    workflows: [Preview Build]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy-site:
    permissions:
      actions: read # for dawidd6/action-download-artifact to query and download artifacts
      issues: write # for actions-cool/maintain-one-comment to modify or create issue comments
      pull-requests: write # for actions-cool/maintain-one-comment to modify or create PR comments
    name: deploy preview
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'


    steps:
      # get PR id first
      - name: Download pr artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: pr

      # save PR id to output
      - name: Save PR id
        id: pr
        run: echo "::set-output name=id::$(<pr-id.txt)"

      - name: Download site artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: site

      - name: Upload surge service
        id: deploy
        run: |
          export DEPLOY_DOMAIN=https://preview-${{ steps.pr.outputs.id }}-oceanbase-design.surge.sh
          npx surge --project ./ --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}

      - name: Update status comment
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            <a href="https://preview-${{ steps.pr.outputs.id }}-oceanbase-design.surge.sh" target="_blank">
              <div
                style="display: inline-block;
                       font-size: 96px;
                       padding: 32px 64px;
                       background-color: #006AFF;
                       color: #fff;
                       border-radius: 16px;
                       box-shadow: 0 6px 16px 0 rgba(54, 69, 99, 0.08), 0 3px 6px -4px rgba(54, 69, 99, 0.12), 0 9px 28px 8px rgba(54, 69, 99, 0.05);
                      "
              >
                ðŸŽ‰ Preview is ready!
              </div>
            </a>
            <!-- AUTO_PREVIEW_HOOK -->
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'
          number: ${{ steps.pr.outputs.id }}

      - name: The job has failed
        if: ${{ failure() }}
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ðŸ˜­ Preview Deploy failed.
            <img width="300" src="https://user-images.githubusercontent.com/507615/90250824-4e066700-de6f-11ea-8230-600ecc3d6a6b.png">
            <!-- AUTO_PREVIEW_HOOK -->
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'
          number: ${{ steps.pr.outputs.id }}

  build-site-failed:
    permissions:
      actions: read # for dawidd6/action-download-artifact to query and download artifacts
      issues: write # for actions-cool/maintain-one-comment to modify or create issue comments
      pull-requests: write # for actions-cool/maintain-one-comment to modify or create PR comments
    name: build preview failed
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'failure'


    steps:
      # get PR id first
      - name: Download pr artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: pr

      # Save PR id to output
      - name: Save PR id
        id: pr
        run: echo "::set-output name=id::$(<pr-id.txt)"

      - name: The job has failed
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            <img width="534" src="https://user-images.githubusercontent.com/5378891/75333447-1e63a280-58c1-11ea-975d-235367fd1522.png">
            <!-- AUTO_PREVIEW_HOOK -->
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'
          number: ${{ steps.pr.outputs.id }}
